=== VicNew/poc_nisc_service_delivery_process_api/src/main/api/schemas/CreatedServiceOrdersMessageSchema.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://example.com/root.json",
  "type": "array",
  "title": "The Root Schema",
  "items": {
    "$id": "#/items",
    "type": "object",
    "title": "The Items Schema",
    "required": [
      "OrderId",
      "CustomerId",
      "ServicesBoundle",
      "Description",
      "Status",
      "links"
    ],
    "properties": {
      "OrderId": {
        "$id": "#/items/properties/OrderId",
        "type": "integer",
        "title": "The Orderid Schema",
        "default": 0,
        "examples": [
          1234
        ]
      },
      "CustomerId": {
        "$id": "#/items/properties/CustomerId",
        "type": "string",
        "title": "The Customerid Schema",
        "default": "",
        "examples": [
          "0123456789"
        ],
        "pattern": "^(.*)$"
      },
      "ServicesBoundle": {
        "$id": "#/items/properties/ServicesBoundle",
        "type": "array",
        "title": "The Servicesboundle Schema",
        "items": {
          "$id": "#/items/properties/ServicesBoundle/items",
          "type": "object",
          "title": "The Items Schema",
          "required": [
            "ServiceId",
            "Description"
          ],
          "properties": {
            "ServiceId": {
              "$id": "#/items/properties/ServicesBoundle/items/properties/ServiceId",
              "type": "string",
              "title": "The Serviceid Schema",
              "default": "",
              "examples": [
                "5"
              ],
              "pattern": "^(.*)$"
            },
            "Description": {
              "$id": "#/items/properties/ServicesBoundle/items/properties/Description",
              "type": "string",
              "title": "The Description Schema",
              "default": "",
              "examples": [
                "Service Description"
              ],
              "pattern": "^(.*)$"
            }
          }
        }
      },
      "Description": {
        "$id": "#/items/properties/Description",
        "type": "string",
        "title": "The Description Schema",
        "default": "",
        "examples": [
          "Service Description"
        ],
        "pattern": "^(.*)$"
      },
      "Status": {
        "$id": "#/items/properties/Status",
        "type": "string",
        "title": "The Status Schema",
        "default": "",
        "examples": [
          "Completed"
        ],
        "pattern": "^(.*)$"
      },
      "links": {
        "$id": "#/items/properties/links",
        "type": "array",
        "title": "The Links Schema",
        "items": {
          "$id": "#/items/properties/links/items",
          "type": "object",
          "title": "The Items Schema",
          "required": [
            "rel",
            "uri",
            "method"
          ],
          "properties": {
            "rel": {
              "$id": "#/items/properties/links/items/properties/rel",
              "type": "string",
              "title": "The Rel Schema",
              "default": "",
              "examples": [
                "/linkrels/serviceOrder/info"
              ],
              "pattern": "^(.*)$"
            },
            "uri": {
              "$id": "#/items/properties/links/items/properties/uri",
              "type": "string",
              "title": "The Uri Schema",
              "default": "",
              "examples": [
                "/service/order/1234"
              ],
              "pattern": "^(.*)$"
            },
            "method": {
              "$id": "#/items/properties/links/items/properties/method",
              "type": "string",
              "title": "The Method Schema",
              "default": "",
              "examples": [
                "GET"
              ],
              "pattern": "^(.*)$"
            }
          }
        }
      }
    }
  }
}

=== VicNew/poc_nisc_service_delivery_process_api/src/main/api/examples/CreatedServiceOrdersMessage.json
[
   {
      "OrderId":1234,
      "CustomerId":"0123456789",
      "ServicesBoundle":[
         {
            "ServiceId":"5",
            "Description":"Service Description"
         },
         {
            "ServiceId":"3",
            "Description":"Service Description"
         }
      ],
      "Description":"Service Description",
      "Status":"Completed",
      "links":[
         {
            "rel":"/linkrels/serviceOrder/info",
            "uri":"/service/order/1234",
            "method":"GET"
         },
         {
            "rel":"/linkrels/serviceOrder/updateInfo",
            "uri":"/service/order/1234",
            "method":"PUT"
         },
         {
            "rel":"/linkrels/serviceOrder/delete",
            "uri":"/service/order/1234",
            "method":"DELETE"
         }
      ]
   },
   {
      "OrderId":5678,
      "CustomerId":"0123456789",
      "ServicesBoundle":[
         {
            "ServiceId":"5",
            "Description":"Service Description"
         },
         {
            "ServiceId":"3",
            "Description":"Service Description"
         }
      ],
      "Description":"Service Description",
      "Status":"Completed",
      "links":[
         {
            "rel":"/linkrels/serviceOrder/info",
            "uri":"/service/order/5678",
            "method":"GET"
         },
         {
            "rel":"/linkrels/serviceOrder/updateInfo",
            "uri":"/service/order/5678",
            "method":"PUT"
         },
         {
            "rel":"/linkrels/serviceOrder/delete",
            "uri":"/service/order/5678",
            "method":"DELETE"
         }
      ]
   }
]
